spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thatsmyspot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  thymeleaf:
    cache: false
  mail:
    host: smtp.example.com
    port: 587
    username: your@email.com
    password: yourpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

# Security
jwt:
  secret: "REPLACE_WITH_A_SECRET_KEY"
  expiration: 86400000 # 1 day in ms

# Logging
logging:
  level:
    org.springframework: INFO
    com.wmu: DEBUG 